"use strict";
(function(){
  const config=window.SUPABASE_CONFIG||{};
  const ready=Boolean(config.url&&config.anonKey&&!String(config.url).includes("YOUR_"));
  const tokenKey="portfolio-cloud-session:"+(config.project||location.pathname);
  let session=null;
  try{session=JSON.parse(localStorage.getItem(tokenKey)||"null")}catch{}
  const headers=()=>({apikey:config.anonKey||"",Authorization:`Bearer ${session?.access_token||config.anonKey||""}`,"Content-Type":"application/json",Prefer:"return=representation"});
  async function request(path,options={}){if(!ready)throw Error("云端尚未配置");const response=await fetch(config.url+path,{...options,headers:{...headers(),...options.headers}});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!response.ok)throw Error(data?.msg||data?.message||data?.error_description||`请求失败 (${response.status})`);return data}
  async function refresh(){if(!session?.refresh_token)return null;try{session=await request("/auth/v1/token?grant_type=refresh_token",{method:"POST",body:JSON.stringify({refresh_token:session.refresh_token})});localStorage.setItem(tokenKey,JSON.stringify(session));return session}catch{logout();return null}}
  function logout(){session=null;localStorage.removeItem(tokenKey);render();window.dispatchEvent(new CustomEvent("cloud-auth",{detail:null}))}
  async function magicLink(email){return request("/auth/v1/otp",{method:"POST",body:JSON.stringify({email,create_user:true,options:{email_redirect_to:location.href.split("#")[0]}})})}
  async function restoreFromHash(){const params=new URLSearchParams(location.hash.slice(1));if(params.get("access_token")){session={access_token:params.get("access_token"),refresh_token:params.get("refresh_token"),expires_at:Math.floor(Date.now()/1000)+Number(params.get("expires_in")||3600)};localStorage.setItem(tokenKey,JSON.stringify(session));history.replaceState(null,"",location.pathname+location.search);window.dispatchEvent(new CustomEvent("cloud-auth",{detail:session}))}if(session?.expires_at&&session.expires_at<Math.floor(Date.now()/1000)+60)await refresh()}
  function userId(){if(!session?.access_token)return null;try{return JSON.parse(atob(session.access_token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/"))).sub}catch{return null}}
  async function rows(table,query=""){return request(`/rest/v1/${table}?${query}`,{headers:{Prefer:""}})}
  async function upsert(table,data){return request(`/rest/v1/${table}?on_conflict=id`,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(data)})}
  async function remove(table,id){return request(`/rest/v1/${table}?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"})}
  function render(){document.querySelectorAll("[data-cloud-status]").forEach(host=>{const online=Boolean(session&&ready);host.innerHTML=`<span class="cloud-pill ${online?"online":""}"><i class="cloud-dot"></i>${online?"云端已连接":ready?"游客模式":"游客模式 · 待配置云端"}</span><button type="button" class="cloud-action" data-cloud-action="${online?"logout":"login"}">${online?"退出":"登录保存"}</button>`})}
  function mount(){if(!document.querySelector("#cloudLogin"))document.body.insertAdjacentHTML("beforeend",`<dialog id="cloudLogin" class="cloud-dialog"><form method="dialog"><h2>登录并保存到云端</h2><p>输入邮箱后，我们会发送一次性登录链接。游客数据仍保留在当前浏览器。</p><label>邮箱地址<input name="email" type="email" autocomplete="email" required placeholder="name@example.com"></label><div class="cloud-message" role="status"></div><menu><button value="cancel" type="submit" class="cloud-action">取消</button><button value="default" type="button" data-send-link>发送登录链接</button></menu></form></dialog>`);document.addEventListener("click",async event=>{const action=event.target.closest("[data-cloud-action]")?.dataset.cloudAction;if(action==="logout")logout();if(action==="login"){const d=document.querySelector("#cloudLogin"),m=d.querySelector(".cloud-message");m.textContent=ready?"":"请先在 config.js 填写该项目的 Supabase 参数。";m.className="cloud-message"+(ready?"":" error");d.showModal()}});document.querySelector("[data-send-link]").addEventListener("click",async()=>{const d=document.querySelector("#cloudLogin"),email=d.querySelector("input").value.trim(),m=d.querySelector(".cloud-message");if(!email||!d.querySelector("input").checkValidity()){d.querySelector("input").reportValidity();return}m.textContent="正在发送…";try{await magicLink(email);m.textContent="登录链接已发送，请检查邮箱。"}catch(e){m.textContent=e.message;m.classList.add("error")}});render()}
  window.PortfolioCloud={ready:()=>ready,session:()=>session,userId,rows,upsert,remove,refresh,render};
  restoreFromHash().finally(()=>{if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount()});
})();
