"use strict";
const analyticsStore="analytics-saved-views";let savedViews=[];try{savedViews=JSON.parse(localStorage.getItem(analyticsStore)||"[]")}catch{}
const filters=()=>({segment:document.querySelector("#segment").value,range:document.querySelector("#range").value});
const metrics=()=>Object.fromEntries(["visitors","signups","activation","conversion"].map(id=>[id,document.querySelector("#"+id).textContent]));
function flash(message){let toast=document.querySelector(".toast-analytics");if(!toast){toast=document.createElement("div");toast.className="toast-analytics";toast.role="status";document.body.append(toast)}toast.textContent=message;clearTimeout(flash.timer);flash.timer=setTimeout(()=>toast.remove(),2500)}
function renderSaved(){let host=document.querySelector("#savedViews");if(!host){host=document.createElement("section");host.id="savedViews";host.className="saved-strip";document.querySelector(".metrics").before(host)}host.innerHTML=savedViews.length?savedViews.map(view=>`<span class="saved-chip"><button type="button" data-load-view="${view.id}" style="color:inherit">${view.name}</button><button type="button" aria-label="删除 ${view.name}" data-remove-view="${view.id}">×</button></span>`).join(""):"<span class=\"compare\">尚未保存分析视图，可保存当前分群和时间范围。</span>"}
function renderComparison(){document.querySelectorAll(".metrics .compare").forEach(node=>node.remove());const group=document.querySelector("#compareSegment").value;if(!group)return;const days=[30,7,90][document.querySelector("#range").selectedIndex],rows=records.filter(row=>row.day<days&&row.segment===group),sum=key=>rows.reduce((total,row)=>total+row[key],0),values=[sum("visits"),sum("signups"),(sum("activated")/Math.max(1,sum("signups"))*100).toFixed(1)+"%",(sum("paid")/Math.max(1,sum("signups"))*100).toFixed(1)+"%"];document.querySelectorAll(".metrics .card").forEach((card,index)=>card.insertAdjacentHTML("beforeend",`<span class="compare">${group}：${typeof values[index]==="number"?values[index].toLocaleString("zh-CN"):values[index]}</span>`))}
async function save(kind){const item={id:crypto.randomUUID(),name:`${filters().segment} · ${document.querySelector("#range").selectedOptions[0].text}`,filters:filters(),metrics:metrics(),created_at:new Date().toISOString()};if(kind==="view"){savedViews.unshift(item);localStorage.setItem(analyticsStore,JSON.stringify(savedViews.slice(0,12)));renderSaved()}const cloud=window.PortfolioCloud,userId=cloud?.userId();if(userId)try{await cloud.upsert(kind==="view"?"saved_views":"analysis_snapshots",[{id:item.id,user_id:userId,name:item.name,filters:item.filters,...(kind==="snapshot"?{metrics:item.metrics}:{})}]);flash(kind==="view"?"视图已保存到云端":"分析快照已保存")}catch(error){flash("本地已保存，云端失败："+error.message)}else flash(kind==="view"?"视图已保存到浏览器":"请登录后保存云端快照")}
document.querySelector("#saveView").addEventListener("click",()=>save("view"));document.querySelector("#snapshot").addEventListener("click",()=>save("snapshot"));document.querySelector("#eventSearch").addEventListener("input",event=>{const q=event.target.value.trim().toLowerCase();document.querySelectorAll("#events tr").forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))});
document.querySelector("#compareSegment").addEventListener("change",renderComparison);["segment","range","refresh"].forEach(id=>document.querySelector("#"+id).addEventListener(id==="refresh"?"click":"change",()=>setTimeout(renderComparison)));
document.addEventListener("click",event=>{const load=event.target.closest("[data-load-view]")?.dataset.loadView,remove=event.target.closest("[data-remove-view]")?.dataset.removeView;if(load){const view=savedViews.find(item=>item.id===load);if(view){document.querySelector("#segment").value=view.filters.segment;document.querySelector("#range").value=view.filters.range;render();flash("已恢复保存的视图")}}if(remove){savedViews=savedViews.filter(item=>item.id!==remove);localStorage.setItem(analyticsStore,JSON.stringify(savedViews));renderSaved()}});
window.addEventListener("cloud-auth",async event=>{if(!event.detail)return;try{const cloudRows=await PortfolioCloud.rows("saved_views","select=id,name,filters,created_at&order=created_at.desc");const ids=new Set(savedViews.map(item=>item.id));savedViews=[...cloudRows.filter(item=>!ids.has(item.id)),...savedViews];localStorage.setItem(analyticsStore,JSON.stringify(savedViews.slice(0,12)));renderSaved();if(savedViews.length)await PortfolioCloud.upsert("saved_views",savedViews.map(item=>({id:item.id,user_id:PortfolioCloud.userId(),name:item.name,filters:item.filters})))}catch(error){flash("云端视图读取失败："+error.message)}});renderSaved();
