create extension if not exists pgcrypto;

create table public.profiles(id uuid primary key references auth.users on delete cascade,display_name text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.resumes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,file_name text not null,content_text text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.jobs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,company text not null default '',role text not null,location text not null default '',salary text not null default '',source_url text not null default '',description text not null default '',status text not null default 'Saved' check(status in ('Saved','Applied','Interview','Offer','Rejected')),priority text not null default 'normal' check(priority in ('high','normal','low')),next_action text not null default '',deadline date,notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.matches(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,resume_id uuid references public.resumes on delete cascade,job_id uuid references public.jobs on delete cascade,score integer not null check(score between 0 and 100),result jsonb not null,model text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.application_packs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,job_id uuid references public.jobs on delete cascade,resume_id uuid references public.resumes on delete cascade,content jsonb not null,model text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.applications(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,job_id uuid not null references public.jobs on delete cascade,submitted_at timestamptz,status text not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.interviews(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,job_id uuid not null references public.jobs on delete cascade,title text not null,scheduled_at timestamptz,notes text not null default '',completed boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.followups(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,job_id uuid not null references public.jobs on delete cascade,title text not null,due_at timestamptz,completed boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table public.ga4_snapshots(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,date_start date not null,date_end date not null,segment text not null default 'all',metrics jsonb not null,rows jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.saved_views(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,name text not null,filters jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.sync_runs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,source text not null check(source in ('ga4','shopify')),status text not null,records integer not null default 0,error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table public.shopify_products(id text not null,user_id uuid not null references auth.users on delete cascade,title text not null,vendor text not null default '',product_type text not null default '',status text not null,inventory_total integer not null default 0,price_min numeric(14,2),price_max numeric(14,2),currency text not null default '',synced_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(id,user_id));
create table public.shopify_inventory(id text not null,user_id uuid not null references auth.users on delete cascade,product_id text not null,sku text not null default '',title text not null default '',quantity integer not null default 0,synced_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(id,user_id));
create table public.shopify_orders(id text not null,user_id uuid not null references auth.users on delete cascade,name text not null,email text not null default '',total numeric(14,2) not null default 0,currency text not null default '',financial_status text not null default '',fulfillment_status text not null default '',placed_at timestamptz,synced_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(id,user_id));
create table public.shopify_customers(id text not null,user_id uuid not null references auth.users on delete cascade,display_name text not null default '',email text not null default '',orders_count integer not null default 0,total_spent numeric(14,2) not null default 0,currency text not null default '',synced_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(id,user_id));
create table public.integration_status(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,provider text not null,status text not null,last_synced_at timestamptz,error text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,provider));
create table public.audit_logs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,action text not null,resource_type text not null,resource_id text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());

alter table public.profiles enable row level security;
create policy "own profile" on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
do $$ declare t text; begin foreach t in array array['resumes','jobs','matches','application_packs','applications','interviews','followups','ga4_snapshots','saved_views','sync_runs','shopify_products','shopify_inventory','shopify_orders','shopify_customers','integration_status','audit_logs'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy "own rows" on public.%I for all using (auth.uid() = user_id) with check (auth.uid() = user_id)',t);end loop;end $$;
